### ISSUE TITLE
How is  'train/ara.training_files.txt' generated and what is the expected content in this file?

### ISSUE THREAD

**Issue by talha1503** [abanoub-hanna/train-tesseract-ocr#1]
Dear Sir , 
I was trying to fine-tune the ara.traineddata from tessdata_best . I have generated my own ara.lstm file . I was trying to use your finetune.sh for fine-tuning but I am getting the following error : 
![Screenshot from 2020-06-18 17-46-24](https://user-images.githubusercontent.com/42352729/85018963-a8df5300-b18b-11ea-9639-6dd4cd051023.png)
Can you please help me out? @abanoub-hanna .

**Comment by talha1503** [comment]
Or else can you please tell the detailed procedure for fin-tuning if we have the ara.traineddata file? @abanoub-hanna

**Comment by abanoubha** [comment]
Is the .lstmf files exist ?
Is the path to them correct ?

_Note_ that **makebox** is not compatible with tesseract 4.0x LSTM training.
